### PR TITLE
Port to netstandard 1.0

### PR DESCRIPTION
**Pull request by jarroda**
This PR ports the project to netstandard 1.0.  The library is configured to compile to both .net 4.5 and netstandard 1.0, so backwards compatibility should be maintained. 

Additionally I ported the test project over and all tests pass that did before, with the same 18 tests failing.  

I am using the .NET Core 1.0.0 SDK - Preview 2.1 (build 003177) tooling.

Once merged, this should address #6 and #13

### CODE REVIEW

**Comment by RichiCoder1** [comment]
Is there a reason you're not using the latest tools? Project.json is officially deprecated as of this point.

**Comment by jarroda** [comment]
@RichiCoder1 Yeah the reason is that I do all my work on macos using VSCode and CLI tooling, and my attempts at using the msbuild based tooling (a couple of weeks ago) found it to be bug-filled and woefully unproductive.  I realize a new release was put out on the 7th, but I haven't had time to mess with it.  

If you'd like to convert it to the most recent tooling, feel free to pitch in.  Opening the solution in VS 2017 will convert it automatically I presume.

**Comment by RichiCoder1** [comment]
Yup. There's also `dotnet migrate`. Luckily the auto conversion has much improved since then. Will look into it.

**Comment by aidanbebbington** [comment]
Thanks for this!  I've just opened it up in VS2017 which converted things it seems.  I've done some basic smoke tests and updated the nuget package.  Let me know if it doesn't work for you.

**Pull request merged**
