### PR TITLE
Zip geocoding data for framework 4.6+

### PR DESCRIPTION
**Pull request by dwfrancis**
Compress geocoding data to reduce dll size to 4608 KB from 14 311 KB for .NET 4.6, .NET Standard 1.3 and .NET Standard 2.0 builds.

### CODE REVIEW

**Comment by dwfrancis** [comment]
The new tests for zipped geocoding fail on the appveyor build but pass locally. I've decompiled the artifact - the preprocessor directives don't seem to be applied.

Could it be an issue using `FRAMEWORK_OR_GREATER`

I can hold off on this PR until the net35 removal is done. That should simplify the preprocessor directives to just be `!PORTABLE`

**Comment by dwfrancis** [comment]
The issue was `{FRAMEWORK}_OR_GREATER` - all looks good now.

**Comment by dwfrancis** [comment]
Fixes large dll sizes - see issue #98

**Comment by dwfrancis** [comment]
@twcclegg  any update on this? Zipping the metadata will significantly reduce the DLL sized needed for offline geocoding.

**Comment by JulianPasque** [comment]
Any plan on merging this PR? @twcclegg

**Comment by patrikwlund** [comment]
Would love to see this merged! 🙌 

Ping @twcclegg

**Comment by twcclegg** [comment]
Sorry I've neglected this. I think once this is rebased I can merge it. Things relating to portable or net framework an be removed.

**Pull request merged**
