### PR TITLE
Improve (unittest) performance by a factor of ~10 (expected real-world improvements to be even higher)

### PR DESCRIPTION
**Pull request by RobThree**
PhoneRegex now uses Lazy<Regex> and the RegexCache now uses a ConcurrentDictionary internally.

I have sacrificed the LRU cache, which is why the TestRegexInsertion currently fails. This means Regexes are currently cached indefinitely. I wonder in how many real-world scenario's caching a few hundred(?) regexes would be an actual problem. Unfortunately I have no numbers on the use of this class nor any idea about the environments this class is used in. But the added complexity of the LRU (and making it thread-safe) seems not worth it to me. Especially if this easy optimization alone results in a 10x improvement.

My numbers for running all unittests went from ~18seconds to ~1.8 seconds on my 9 year old workstation. Will discuss further in #136

### CODE REVIEW

**Comment by RobThree** [comment]
[In my tests](https://github.com/twcclegg/libphonenumber-csharp/issues/136#issuecomment-1313909023) with real world data I've seen an performance improvement of about a factor 70 in, at least, parsing the phonenumbers.

**Comment by twcclegg** [comment]
Assuming this is good to go, I'm happy to merge. Thanks!

**Comment by RobThree** [comment]
You may want to check my [remarks here](https://github.com/twcclegg/libphonenumber-csharp/issues/136#issuecomment-1314149456) but, yes, this should be good to go 🚀

**Comment by RobThree** [comment]
Hi @twcclegg 

Was there a problem merging? Or did you just not get around to it? If there's anything I can do to help, please let me know.

**Comment by twcclegg** [comment]
I didn't get notifications of either of the last two messages for some reason :( , so that would be why.
Thanks again.

**Comment by RobThree** [comment]
No worries and thank **you**!

**Pull request merged**
